name: "build-test-distribute"
on:
#  push:
#    branches: ["master", "release-*", "!*-merge-master"]
#    tags: ["*"]
#  pull_request:
#    branches: ["master", "release-*"]
  workflow_dispatch: # Allows manual trigger from GitHub Actions UI or via REST call
permissions:
  contents: write # To upload assets
  id-token: write # For using token to sign images
  actions: read # For getting workflow run info to build provenance
  packages: write # Required for publishing provenance. Issue: https://github.com/slsa-framework/slsa-github-generator/tree/main/internal/builders/container#known-issues
env:
  KUMA_DIR: "."
  # To keep CI tools out of the SBOM, we use a `.ci_tools` directory in the parent
  # of the code checkout path (typically /home/runner/work/<repo-name>/<repo-name>
  # on the runner).
  CI_TOOLS_DIR: "/home/runner/work/kuma/.ci_tools"
jobs:
  check:
    permissions:
      contents: read
      # golangci-lint-action
      checks: write
    timeout-minutes: 25
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          fetch-depth: 0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version-file: go.mod
          cache: false
      - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
        with:
          args: --fix=false --verbose
          version: v1.61.0
