name: ci-stability-release-branches

on:
  schedule:
    - cron: "*/5 19-0 * * *" # Every 5 minutes between 19:00 and 00:55 UTC
    - cron: "5 1 * * *"      # Cleanup at 1:05 UTC
  workflow_dispatch:
    inputs:
      force_run:
        description: "Force run the workflow outside the schedule"
        required: false
        type: boolean

permissions:
  contents: read

env:
  REPOSITORY_VARIABLE_NAME: TEMP_CI_STABILITY_BRANCHES_TO_PROCESS

jobs:
  should-skip:
    runs-on: ubuntu-24.04
    outputs:
      skip_workflow: ${{ steps.set-skip-workflow.outputs.skip_workflow }}
    permissions:
      actions: read # required to check the status of workflow runs
    steps:
      - id: check-cleanup-run
        env:
          IS_CLEANUP_RUN: ${{ github.event.schedule == '5 1 * * *' }}
        run: |
          if [ "$IS_CLEANUP_RUN" == "true" ]; then
            echo "Cleanup run. Skipping other jobs."
            echo "skip_workflow=true" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "skip_workflow=false" >> $GITHUB_OUTPUT

      - id: check-force-run
        if: steps.check-cleanup-run.outputs.skip_workflow == 'false'
        env:
          FORCE_RUN_TRIGGERED: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.force_run == 'true' }}
        run: |
          if [ "$FORCE_RUN_TRIGGERED" == "true" ]; then
            echo "Force run triggered via workflow_dispatch. Proceeding with the workflow."
            echo "skip_workflow=false" >> $GITHUB_OUTPUT
            exit 0
          fi
          echo "skip_workflow=false" >> $GITHUB_OUTPUT

      - id: check-existing-runs
        if: steps.check-cleanup-run.outputs.skip_workflow == 'false' && steps.check-force-run.outputs.skip_workflow == 'false'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RUNNING=$(gh run list \
            --workflow ci-stability-release-branches.yaml \
            --json status \
            --jq '[
              .[] | select(
                .status | IN(
                  "completed", 
                  "failure", 
                  "cancelled", 
                  "timed_out", 
                  "neutral", 
                  "skipped"
                ) | not
              )
            ] | length' 2>&1)

          if [[ "$RUNNING" =~ "could not find any workflows" || "$RUNNING" =~ ^0$ ]]; then
            echo "skip_workflow=false" >> $GITHUB_OUTPUT
          elif [[ "$RUNNING" =~ ^[0-9]+$ && "$RUNNING" -gt 0 ]]; then
            echo "> [!NOTE]" >> $GITHUB_STEP_SUMMARY
            echo "> There are existing workflows in progress" >> $GITHUB_STEP_SUMMARY
            echo "skip_workflow=true" >> $GITHUB_OUTPUT
          else
            echo "> [!CAUTION]" >> $GITHUB_STEP_SUMMARY
            echo "> Failed to list the workflow runs: $RUNNING" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - id: set-skip-workflow
        run: |
          if [ "${{ steps.check-cleanup-run.outputs.skip_workflow }}" == "true" ] || \
             [ "${{ steps.check-force-run.outputs.skip_workflow }}" == "true" ] || \
             [ "${{ steps.check-existing-runs.outputs.skip_workflow }}" == "true" ]; then
            echo "skip_workflow=true" >> $GITHUB_OUTPUT
          else
            echo "skip_workflow=false" >> $GITHUB_OUTPUT
          fi
