name: "Push"

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  inform-kong-mesh-about-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jwalton/gh-find-current-pr@v1
      id: findPR
      with:
        state: all

    - name: "Add backport label"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const parsePR = require('./.github/scripts/parsePR.js');
          const owner = 'bartsmykla';
          const kumaRepoName = 'kuma';

          console.log({ context });

          const { before, after, commits = [] } = context.payload;
          const pr = await parsePR({ github, owner, kumaRepoName }, ${{ toJSON(steps.findPR.outputs) }});

          console.log("pr", pr);

          github.rest.repos.createDispatchEvent({
            owner,
            repo: 'kong-mesh',
            event_type: 'abracadabra',
            client_payload: {
              before,
              after,
              pr,
              commits: commits.map(({ id }) => id),
            },
          });
