name: "Push"

on:
  push:
    branches:
    - master
    - release-*

  workflow_dispatch:

jobs:
  notify-about-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 # necessary to have access to scripts directory

    - uses: jwalton/gh-find-current-pr@v1
      id: findPR
      with:
        state: all

    - name: "Notify other repositories about push to master"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.NOTIFY_GH_TOKEN }}
        script: |
          const parsePR = require('./.github/scripts/parsePR.js');
          const { payload = {} } = context;
          const { repository = {}, before, after, commits = [] } = payload;
          const { full_name: fullName } = repository;
          const [ owner, repo ] = fullName.split('/');
          const pr = await parsePR(
            { github, owner, repo },
            ${{ toJSON(steps.findPR.outputs) }},
          );

          console.log("context", context);

          github.rest.repos.createDispatchEvent({
            owner: '${{ secrets.NOTIFY_OWNER }}',
            repo: '${{ secrets.NOTIFY_REPO }}',
            event_type: '${{ secrets.NOTIFY_EVENT_TYPE }}',
            client_payload: {
              before,
              after,
              pr,
              commits: commits.map(({ id }) => id),
            },
          });
