name: "Push"

on:
  push:
    branches:
    - master

  workflow_dispatch:

jobs:
  inform-kong-mesh-about-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: jwalton/gh-find-current-pr@v1
      id: findPR
      with:
        state: all

    - name: "Add backport label"
      uses: actions/github-script@v5
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const owner = 'bartsmykla';
          console.log("hello world");
          console.log({ context });

          const { before, after, commits = [] } = context.payload;

          const pr = ${{ toJSON(steps.findPR.outputs) }};

          console.log("pr", pr);

          // TODO: add error checking
          const fullPR = await github.rest.pulls.get({
            owner,
            repo: 'kuma',
            pull_number: pr.number,
          });

          const { data = {} } = fullPR;

          const {
            user = {},
            merged_by: mergedBy = {},
            labels = [],
          } = data

          console.log("fullPR", fullPR);
          console.log("labels", labels);

          github.rest.repos.createDispatchEvent({
            owner,
            repo: 'kong-mesh',
            event_type: 'abracadabra',
            client_payload: {
              before,
              after,
              pr: {
                number: pr.number,
                title: pr.title,
                openedBy: {
                  login: user.login,
                  id: user.id,
                },
                mergedBy: {
                  login: mergedBy.login,
                  id: mergedBy.id,
                },
              },
              commits: commits.map(({ id }) => id),
            },
          });
